#!/usr/bin/env python3
"""
Document Preparation Script for Typst PDF Maker Skill.
Sets up project directory structure with main.typ, report-theme.typ, and manifest.
"""

import os
import sys
import argparse
import json

def prepare_project(target_dir, title, subtitle, author):
    os.makedirs(target_dir, exist_ok=True)
    
    # 1. Write manifest
    manifest = {
        "task_kind": "new-document",
        "output": "pdf",
        "signals": ["executive-report"],
        "hard_constraints": [],
        "content_features": {
            "code_blocks": 2,
            "defined_terms": 4,
            "portrait_images": 0
        }
    }
    with open(os.path.join(target_dir, ".typst-content-manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    # 2. Write main.typ
    main_typ_content = f"""// Typst Main Document Entry
// Generated by prepare_document.py

#import "report-theme.typ": *

#show: report-theme.with(
  title: "{title}",
  subtitle: "{subtitle}",
  author: "{author}",
  date: datetime.today().display("[Month repr:long] [Year]")
)

= Executive Overview

This document outlines the core operational standards and architectural specifications.

#metric-grid(
  ("Inference Throughput", "1,420 tps", "+38% YoY"),
  ("E2E Task Latency", "184 ms", "-42% Reduction"),
  ("Context Precision", "99.4%", "+2.1% Improvement")
)

#callout(title: "KEY ARCHITECTURAL HIGHLIGHT")[
  Localized execution and state graph compaction reduce synchronization overhead by 64%, enabling sub-200ms SLAs.
]

= 1. High-Throughput Infrastructure

The architecture operates across decoupled inference, context, and safety planes.

#table(
  columns: (1.2fr, 2.5fr, 1fr),
  fill: (x, y) => if y == 0 {{ rgb("#1E40AF") }} else if calc.even(y) {{ rgb("#F8FAFC") }} else {{ white }},
  stroke: 0.5pt + rgb("#E2E8F0"),
  [*Component Layer*], [*Key Responsibilities*], [*Status*],
  [Agent Core Loop], [Executes tool-use plans and retry policies.], [Production],
  [Context Fabric], [Semantic vector index with graph memory.], [Optimized],
  [Safety Verification], [Real-time policy checks and PII masking.], [Active]
)

= 2. Implementation Reference

```rust
pub async fn dispatch_task_pipeline(task: TaskRequest) -> Result<ExecutionSummary, AgentError> {{
    let context = ContextEngine::hydrate_session(&task.session_id).await?;
    let plan = AgentPlanner::decompose_query(&task.prompt, &context).await?;
    Ok(plan.execute().await?)
}}
```

"""
    with open(os.path.join(target_dir, "main.typ"), "w") as f:
        f.write(main_typ_content)

    # 3. Write report-theme.typ
    theme_content = """// Report Theme Component Definitions
#let brand-color = rgb("#0F172A")
#let primary-blue = rgb("#1E40AF")
#let accent-teal = rgb("#0D9488")
#let bg-soft = rgb("#F8FAFC")
#let border-color = rgb("#E2E8F0")

#let report-theme(
  title: "",
  subtitle: "",
  author: "",
  date: "",
  body
) = {
  set document(title: title, author: author)
  set page(
    paper: "a4",
    margin: (x: 2cm, top: 2.5cm, bottom: 2.5cm),
    header: context {
      if counter(page).get().first() > 1 [
        #grid(
          columns: (1fr, auto),
          align(left)[#text(size: 8.5pt, fill: rgb("#64748B"))[#title]],
          align(right)[#text(size: 8.5pt, fill: rgb("#64748B"))[Technical Whitepaper]]
        )
        #v(-4pt)
        #line(length: 100%, stroke: 0.5pt + border-color)
      ]
    },
    footer: context {
      if counter(page).get().first() > 1 [
        #line(length: 100%, stroke: 0.5pt + border-color)
        #v(2pt)
        #grid(
          columns: (1fr, auto),
          align(left)[#text(size: 8.5pt, fill: rgb("#64748B"))[CONFIDENTIAL]],
          align(right)[#text(size: 8.5pt, fill: rgb("#64748B"), weight: "bold")[Page #counter(page).get().first()]]
        )
      ]
    }
  )

  set text(font: ("Liberation Sans", "Helvetica"), size: 10pt, fill: rgb("#334155"))

  // Title Block
  align(center)[
    #block(fill: brand-color, inset: (x: 20pt, y: 14pt), radius: 4pt)[
      #text(fill: white, size: 9pt, weight: "bold")[EXECUTIVE TECHNICAL REPORT]
    ]
    #v(0.8cm)
    #text(size: 22pt, weight: "bold", fill: brand-color)[#title]
    #v(0.4cm)
    #text(size: 11pt, fill: rgb("#475569"))[#subtitle]
    #v(0.8cm)
    #line(length: 40%, stroke: 1.5pt + primary-blue)
    #v(0.4cm)
    #text(size: 8.5pt, fill: rgb("#64748B"))[Author: #author | Date: #date]
  ]

  v(1cm)
  body
}

#let callout(title: "NOTE", body) = {
  block(
    fill: rgb("#F1F5F9"),
    stroke: (left: 4pt + accent-teal),
    inset: (x: 14pt, y: 10pt),
    radius: (right: 4pt),
    width: 100%,
    [
      #text(weight: "bold", size: 9pt, fill: accent-teal)[#title]
      #v(2pt)
      #text(size: 9.5pt)[#body]
    ]
  )
}

#let metric-grid(..items) = {
  grid(
    columns: items.pos().map(_ => 1fr),
    gutter: 12pt,
    ..items.pos().map(item => {
      block(
        fill: bg-soft,
        stroke: 1pt + border-color,
        inset: 12pt,
        radius: 6pt,
        width: 100%,
        [
          #text(size: 8.5pt, fill: rgb("#64748B"), weight: "medium")[#item.at(0)]
          #v(2pt)
          #text(size: 15pt, weight: "bold", fill: brand-color)[#item.at(1)]
          #v(2pt)
          #text(size: 8.5pt, weight: "bold", fill: rgb("#16A34A"))[#item.at(2)]
        ]
      )
    })
  )
}
"""
    with open(os.path.join(target_dir, "report-theme.typ"), "w") as f:
        f.write(theme_content)

    print(f"[SUCCESS] Project prepared in {target_dir}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('target_dir', help='Target directory for document project')
    parser.add_argument('--title', default='Next-Generation Systems Architecture', help='Document title')
    parser.add_argument('--subtitle', default='Technical Whitepaper & Deployment Guide', help='Document subtitle')
    parser.add_argument('--author', default='Systems Architecture Group', help='Author name')
    args = parser.parse_args()

    prepare_project(args.target_dir, args.title, args.subtitle, args.author)
